Repository CA-G12/Quiz-app-Abood-Mai-Saif, pull requests merged in 2022-07, with the labels that each got.

#2 create file structure
  Questions.html
  index.html
  leaderBoard.html
  script.js
  startQuiz.html
  style.css
Labels: awaiting-review

#6 Make description page add html page and style page for it
  index.html
  style.css
Labels: awaiting-review

#7 make startQuiz page with html and css
  startQuiz.html
  style.css
Labels: done

#10 make leaderboard file with html and css
  leaderBoard.html
  style.css
Labels: done

#12 make java script code and edit some css and html and save to local so…
  Questions.html
  index.html
  leaderBoard.html
  leaderBoard.js
  questions.js
  script.js
  startQuiz.html
  style.css
Labels: done

#14 add readme file and all details about my quiz app
  README.md
Labels: in-progress
